### ISSUE TITLE
More shadow settings (if possible of course)

### ISSUE THREAD

**Issue by AnticOwl** [etra0/litcher#9]
Settings like:

- Shadow slope
- Bias
- etc.

**Comment by etra0** [comment]
Ok so I did a bit further exploration and I've discovered these variables:

* Shadow Blend
* Attenuation
* Shadow fade distance
* Shadow fade range

Which are generic to the lights (i.e. pointlights and spotlights use them). Of those 4, only the first two made sense to use, because Shadow fade distance and Shadow fade range were related to the rendering engine to select at what distance the shadow should be rendered.

I'll add control units for the first two and then I'll close this issue.
